paths:
  /follow:
    post:
      tags:
        - Mypage
      summary: 이웃 추가(구독)
      parameters:
        - name: add neighbor
          in: body
          required: true
          schema:
            properties:
              followId:
                type: varchar(10)
                description: 사용자 일련번호
                example: 15
              
      responses:
        '200':
          description: 이웃 생성 성공!
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 200
              message:
                type: string
                example: "success!"
              result:
                type: object
                example: {
                  "id": 20,
                  "user_id": "1",
                  "follow_id": "15",
                  
                  }

        '400':
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다

        '500':
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.

    