paths:
  /signup:
    post:
      tags:
        - User
      summary: 회원가입
      parameters:
        - name: signup
          in: body
          required: true
          schema:
            properties:
              name:
                type: varchar(10)
                description: 유저 이름
                example: 호로롱
              nickname:
                type: varchar(50)
                description: 유저 닉네임
                example: 호이호이
              email:
                type: varchar(50)
                description: 유저 이메일
                example: example4@example.com
              pw:
                type: varchar(100)
                description: 유져 비밀번호
                example: 2346732
              pwcheck:
                type: varchar(100)
                description: 유져 비밀번호 확인
                example: 2346732
              phone:
                type: varchar(15)
                description: 유저 휴대폰
                example: 01094782943
              b_date:
                type: date
                description: 생년월일
                example: 20040307
              alarm:
                type: boolean
                description: 알람 약관 동의
                example: False
      responses:
        '200':
          description: 회원 가입 성공!
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              data:
                type: object
                example: {
                  "nickname": " ",
                }

        '400':
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다

        '500':
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.